### ISSUE TITLE
Situation where an exception happens while parsing JSON request

### ISSUE THREAD

**Issue by lrxw** [zalando/problem-spring-web#206]
I'm curious about the order of execution when a JSON parse exceptions happens. We build our ProblemModule with an configurable boolean `withStackTraces` in a Spring 4 application.
```
@Override
protected void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
	super.configureMessageConverters(converters);
	ObjectMapper mapper = Jackson2ObjectMapperBuilder.json().modules(new ProblemModule().withStackTraces(withStackTraces)).build();
	converters.add(new MappingJackson2HttpMessageConverter(mapper));
}
```
In a dev environment we enable stacktraces and in a production environment we set the boolean to false. So we don't leak any information with our public service.
Unfortunatly, we have a situation now, that I don't understand entirely.
If there happens an exception while parsing wrong JSON in the request, there will always be a JSON response sent to the client with a stacktrace no matter if we call `ProblemModule().withStackTraces(true)` or `ProblemModule().withStackTraces(false)`.

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String "test": not a valid Long value
at [Source: (PushbackInputStream); line: 2, column: 8] (through reference chain: java.util.ArrayList[0]->test.Dto["id"])
      at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
      at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1548)
      at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:910)
      at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer._parseLong(NumberDeserializers.java:584)
      at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:557)
      at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:535)
      at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
      at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:368)
      at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
      at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
      at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
      at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
      at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
      at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3072)
      at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:235)
      ... 43 more
```
It seems, the ObjectMapper is not called(because the Mixins do not take effect), but the `ExceptionHandler` from the `AdviceTrait`. Is that correct? Is there any way to enable and disable stacktraces? Do you have any information about the order of execution in Spring regarding MessageConverters and ExceptionHandler(incoming and outgoing)?

**Comment by whiskeysierra** [comment]
Can you include the response body?

**Comment by lrxw** [comment]
I shortened the stacktrace:
```
{
    "cause": null,
    "stackTrace": [
        ...
    ],
    "type": "about:blank",
    "title": "Bad Request",
    "status": "BAD_REQUEST",
    "detail": "JSON parse error: Cannot deserialize value of type `java.lang.Long` from String \"test\": not a valid Long value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String \"test\": not a valid Long value\n at [Source: (PushbackInputStream); line: 2, column: 8] (through reference chain: java.util.ArrayList[0]->test.Dto[\"id\"])",
    "instance": null,
    "parameters": {},
    "message": "Bad Request: JSON parse error: Cannot deserialize value of type `java.lang.Long` from String \"test\": not a valid Long value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String \"test\": not a valid Long value\n at [Source: (PushbackInputStream); line: 2, column: 8] (through reference chain: java.util.ArrayList[0]->test.Dto[\"id\"])",
    "localizedMessage": "Bad Request: JSON parse error: Cannot deserialize value of type `java.lang.Long` from String \"test\": not a valid Long value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String \"test\": not a valid Long value\n at [Source: (PushbackInputStream); line: 2, column: 8] (through reference chain: java.util.ArrayList[0]->test.Dto[\"id\"])",
    "suppressed": []
}
```

**Comment by lrxw** [comment]
Which is the one and only? I thought with overwriting `configureMessageConverters` that the `ObjectMapper` I created became the one and only.
Did your documented way of adding a module change? I remember an example where the `ProblemModule` was registered on a newly created `ObjectMapper`. Now I see only a bean definition of the module.
And is the recommended way for Spring 4 and Sprinng Boot the same?

**Comment by whiskeysierra** [comment]
Spring 4/Boot 1.x:
- either create an ObjectMapper by hand and configure the modules you need
- or use `Jackson2ObjectMapperBuilder`

Spring 5/Boot 2.x:
- register modules as beans
- or use any of the two methods above

> I thought with overwriting configureMessageConverters that the ObjectMapper I created became the one and only.

That should work. Can you share you configuration code?

**Comment by lrxw** [comment]
We have an older application which mixed Java and XML config. While I tried to build a small sample to reproduce the error I found out that there was the xml tag `<mvc:annotation-driven />`. After deleting it, it worked. Thank you for your help.
